### PR TITLE
Create README_KR.md

### PR DESCRIPTION
**Pull request by DDinghoya**

### CODE REVIEW

**Comment by DarkMatterCore** [comment]
@DDinghoya Looks good to me. I noticed there are some parts from the v1.0.6 changelog that were left untranslated - was this intentional?

Other than that, a *big* update is coming very soon, so you may want to wait until I push the changes.

**Comment by DDinghoya** [comment]
Thank you for your reply!

I missed some part from the v1.0.6 and As  you mention, I'll wait next update!

**Comment by DarkMatterCore** [comment]
New version has been released. Please check it out!

**Comment by DDinghoya** [comment]
Done! :)

**Comment by DarkMatterCore** [comment]
Thanks! It's now merged into the master branch. :)

**Pull request merged**
